stages:
  train:
    cmd: python src/pipeline/process.py params.yaml
    deps:
      - data/raw
      - src
    outs:
      - data/dvc/
    metrics:
      - models/metrics.json:
          cache: false