stages:
  train:
    cmd:
      - python src/pipeline/run.py params.yaml
      - python src/pipeline/submission.py params.yaml
    deps:
      - src
      - params.yaml
    outs:
      - data/dvc/
    metrics:
      - models/metrics-train.json:
          cache: false