train:
  data:
    train:
      path: data/raw/train.csv
    predict:
      path: data/raw/test.csv
  preproc:
    missing: most_frequent
    corr_threshold: null
    outliers_removal: True
    distribution_lambda: 0
    bins_years:
      cols: []
      cnt: 0

  estimator:
    name: XGBRegressor
  steps:
    cv: true
    grid: False
  eval:
    feature_importance: False
dvc:
  auto:
    dir: data/dvc/
    path: data/dvc/train_dict.pkl
  metrics:
    train:
      path: models/metrics-train.json
    final:
      path: models/metrics-final.json