prepare:
  data:
    train:
      path: data/raw/train.csv
    predict:
      path: data/raw/test.csv
  preproc:
    missing: most_frequent
    corr_threshold: none
    outliers_removal: True
    target_transform:
      enabled: True
      lambda: 0
  train:
    name: LinearRegression
dvc:
  auto:
    dir: data/dvc/
    path: data/dvc/train_dict.pkl
  metrics:
    train:
      path: models/metrics-train.json
    final:
      path: models/metrics-final.json