prepare:
  data:
    input:
      path: data/raw/train.csv
  preproc:
    missing: freq
  train:
    name: LinearRegression
dvc:
  auto:
    dir: data/dvc/
    path: data/dvc/train_dict.pkl
  metrics:
    path: models/metrics.json