train:
  data:
    train:
      path: data/raw/train.csv
    predict:
      path: data/raw/test.csv
  preproc:
    missing: most_frequent
    corr_threshold: null
    outliers_removal: True
    distribution_lambda: 0
  estimator:
    name: XGBRegressor
    grid: False
dvc:
  auto:
    dir: data/dvc/
    path: data/dvc/train_dict.pkl
  metrics:
    train:
      path: models/metrics-train.json
    final:
      path: models/metrics-final.json